- hosts: peweb

  environment:
          OSArchitecture: x86_64

  tasks:

    - name: unzip LG archive
      unarchive:
        src: /Users/pe/Installer/MF_LG_1260_Linux_64bit.tar
        dest: /tmp

    # MF Loadrunner Installer run: installer.sh -i silent
    - name: Install LG
      shell: chdir=/tmp/MF_LG_1260_Linux_64bit/lg_linux_x64/ ./installer.sh -i silent >> /tmp/LGInstaller.log
      become: yes
      args:

# PostInstall
# .cd /opt/MF/MF_LoadGenerator/;source env.sh;cd bin;./m_daemon_setup -install

    - name: environment
      shell: chdir=/opt/MF/MF_LoadGenerator/ ./env.sh
      become: yes
      args:

    - name: m_daemon_setup install
      shell: chdir=/opt/MF/MF_LoadGenerator/bin  ./m_daemon_setup -install
      become: yes
      args:
